# Cloudflare Pages + D1 analytics
name = "cinemap-web"
compatibility_date = "2024-11-01"
pages_build_output_dir = "out"

[[d1_databases]]
binding = "DB"
database_name = "cinemap-analytics"
database_id = "ea84ed15-ee58-4dca-8b8c-a13ffc65f083"
